import SwingTradeGraph from '../assets/Home/swingTradeGraph.webp';


// Mock data for the trading cards
export const tradingData = [
    {
        symbol: "Alpha.X",
        name: "Alpha.X",
        mark: "+38.7%",
        signalDate: "15 Sep 2025",
        expectedProphit: "Expected profit",
        statusColor: "bg-red-500",
        targetBuy: "$24.56",
        stopLoss: "$24.56",
        mostRecentExit: "$24.63",
        targetSale1: "$24.63",
        targetSale2: "$23.58",
        realizedGained: "+38.7%",
        unrealizedGained: "0%",
        chart: SwingTradeGraph
    },
    {
        symbol: "Beta.Y",
        name: "Beta Enterprices",
        mark: "+42.10%",
        signalDate: "15 Sep 2025",
        expectedProphit: "Possible gain",
        statusColor: "bg-red-500",
        targetBuy: "$40.256",
        stopLoss: "$37.466",
        mostRecentExit: "---",
        targetSale1: "$45.350",
        targetSale2: "$49.500",
        realizedGained: "-10.200%",
        unrealizedGained: "0%",
        chart: SwingTradeGraph
    },
    {
        symbol: "Gamma.Z",
        name: "Gamma Solutions",
        mark: "+22.10%",
        signalDate: "15 Sep 2025",
        expectedProphit: "Expected profit",
        statusColor: "bg-red-500",
        targetBuy: "$33.120",
        stopLoss: "$30.000",
        mostRecentExit: "---",
        targetSale1: "$40.320",
        targetSale2: "$49.500",
        realizedGained: "-12.542%",
        unrealizedGained: "0%",
        chart: SwingTradeGraph
    },
    {
        symbol: "AMZN.O",
        name: "Amazon Inc",
        mark: "+98.21%",
        signalDate: "15 Sep 2025",
        expectedProphit: "Expected profit",
        statusColor: "bg-red-500",
        targetBuy: "$40.256",
        stopLoss: "$37.466",
        mostRecentExit: "---",
        targetSale1: "$45.350",
        targetSale2: "$49.500",
        realizedGained: "-10.200%",
        unrealizedGained: "0%",
        chart: SwingTradeGraph
    },
    {
        symbol: "Alpha.X",
        name: "Alpha.X",
        mark: "+38.7%",
        signalDate: "15 Sep 2025",
        expectedProphit: "Expected profit",
        statusColor: "bg-red-500",
        targetBuy: "$24.56",
        stopLoss: "$24.56",
        mostRecentExit: "$24.63",
        targetSale1: "$24.63",
        targetSale2: "$23.58",
        realizedGained: "+38.7%",
        unrealizedGained: "0%",
        chart: SwingTradeGraph
    },
    {
        symbol: "Beta.Y",
        name: "Beta Enterprices",
        mark: "+42.10%",
        signalDate: "15 Sep 2025",
        expectedProphit: "Possible gain",
        statusColor: "bg-red-500",
        targetBuy: "$40.256",
        stopLoss: "$37.466",
        mostRecentExit: "---",
        targetSale1: "$45.350",
        targetSale2: "$49.500",
        realizedGained: "-10.200%",
        unrealizedGained: "0%",
        chart: SwingTradeGraph
    },
    {
        symbol: "Gamma.Z",
        name: "Gamma Solutions",
        mark: "+22.10%",
        signalDate: "15 Sep 2025",
        expectedProphit: "Expected profit",
        statusColor: "bg-red-500",
        targetBuy: "$33.120",
        stopLoss: "$30.000",
        mostRecentExit: "---",
        targetSale1: "$40.320",
        targetSale2: "$49.500",
        realizedGained: "-12.542%",
        unrealizedGained: "0%",
        chart: SwingTradeGraph
    },
    {
        symbol: "AMZN.O",
        name: "Amazon Inc",
        mark: "+98.21%",
        signalDate: "15 Sep 2025",
        expectedProphit: "Expected profit",
        statusColor: "bg-red-500",
        targetBuy: "$40.256",
        stopLoss: "$37.466",
        mostRecentExit: "---",
        targetSale1: "$45.350",
        targetSale2: "$49.500",
        realizedGained: "-10.200%",
        unrealizedGained: "0%",
        chart: SwingTradeGraph
    },
    {
        symbol: "Alpha.X",
        name: "Alpha.X",
        mark: "+38.7%",
        signalDate: "15 Sep 2025",
        expectedProphit: "Expected profit",
        statusColor: "bg-red-500",
        targetBuy: "$24.56",
        stopLoss: "$24.56",
        mostRecentExit: "$24.63",
        targetSale1: "$24.63",
        targetSale2: "$23.58",
        realizedGained: "+38.7%",
        unrealizedGained: "0%",
        chart: SwingTradeGraph
    },
    {
        symbol: "Beta.Y",
        name: "Beta Enterprices",
        mark: "+42.10%",
        signalDate: "15 Sep 2025",
        expectedProphit: "Possible gain",
        statusColor: "bg-red-500",
        targetBuy: "$40.256",
        stopLoss: "$37.466",
        mostRecentExit: "---",
        targetSale1: "$45.350",
        targetSale2: "$49.500",
        realizedGained: "-10.200%",
        unrealizedGained: "0%",
        chart: SwingTradeGraph
    },
    {
        symbol: "Gamma.Z",
        name: "Gamma Solutions",
        mark: "+22.10%",
        signalDate: "15 Sep 2025",
        expectedProphit: "Expected profit",
        statusColor: "bg-red-500",
        targetBuy: "$33.120",
        stopLoss: "$30.000",
        mostRecentExit: "---",
        targetSale1: "$40.320",
        targetSale2: "$49.500",
        realizedGained: "-12.542%",
        unrealizedGained: "0%",
        chart: SwingTradeGraph
    },
    {
        symbol: "AMZN.O",
        name: "Amazon Inc",
        mark: "+98.21%",
        signalDate: "15 Sep 2025",
        expectedProphit: "Expected profit",
        statusColor: "bg-red-500",
        targetBuy: "$40.256",
        stopLoss: "$37.466",
        mostRecentExit: "---",
        targetSale1: "$45.350",
        targetSale2: "$49.500",
        realizedGained: "-10.200%",
        unrealizedGained: "0%",
        chart: SwingTradeGraph
    },
    {
        symbol: "Alpha.X",
        name: "Alpha.X",
        mark: "+38.7%",
        signalDate: "15 Sep 2025",
        expectedProphit: "Expected profit",
        statusColor: "bg-red-500",
        targetBuy: "$24.56",
        stopLoss: "$24.56",
        mostRecentExit: "$24.63",
        targetSale1: "$24.63",
        targetSale2: "$23.58",
        realizedGained: "+38.7%",
        unrealizedGained: "0%",
        chart: SwingTradeGraph
    },
    {
        symbol: "Beta.Y",
        name: "Beta Enterprices",
        mark: "+42.10%",
        signalDate: "15 Sep 2025",
        expectedProphit: "Possible gain",
        statusColor: "bg-red-500",
        targetBuy: "$40.256",
        stopLoss: "$37.466",
        mostRecentExit: "---",
        targetSale1: "$45.350",
        targetSale2: "$49.500",
        realizedGained: "-10.200%",
        unrealizedGained: "0%",
        chart: SwingTradeGraph
    },
    {
        symbol: "Gamma.Z",
        name: "Gamma Solutions",
        mark: "+22.10%",
        signalDate: "15 Sep 2025",
        expectedProphit: "Expected profit",
        statusColor: "bg-red-500",
        targetBuy: "$33.120",
        stopLoss: "$30.000",
        mostRecentExit: "---",
        targetSale1: "$40.320",
        targetSale2: "$49.500",
        realizedGained: "-12.542%",
        unrealizedGained: "0%",
        chart: SwingTradeGraph
    },
    {
        symbol: "AMZN.O",
        name: "Amazon Inc",
        mark: "+98.21%",
        signalDate: "15 Sep 2025",
        expectedProphit: "Expected profit",
        statusColor: "bg-red-500",
        targetBuy: "$40.256",
        stopLoss: "$37.466",
        mostRecentExit: "---",
        targetSale1: "$45.350",
        targetSale2: "$49.500",
        realizedGained: "-10.200%",
        unrealizedGained: "0%",
        chart: SwingTradeGraph
    },
    {
        symbol: "Alpha.X",
        name: "Alpha.X",
        mark: "+38.7%",
        signalDate: "15 Sep 2025",
        expectedProphit: "Expected profit",
        statusColor: "bg-red-500",
        targetBuy: "$24.56",
        stopLoss: "$24.56",
        mostRecentExit: "$24.63",
        targetSale1: "$24.63",
        targetSale2: "$23.58",
        realizedGained: "+38.7%",
        unrealizedGained: "0%",
        chart: SwingTradeGraph
    },
    {
        symbol: "Beta.Y",
        name: "Beta Enterprices",
        mark: "+42.10%",
        signalDate: "15 Sep 2025",
        expectedProphit: "Possible gain",
        statusColor: "bg-red-500",
        targetBuy: "$40.256",
        stopLoss: "$37.466",
        mostRecentExit: "---",
        targetSale1: "$45.350",
        targetSale2: "$49.500",
        realizedGained: "-10.200%",
        unrealizedGained: "0%",
        chart: SwingTradeGraph
    },
    {
        symbol: "Gamma.Z",
        name: "Gamma Solutions",
        mark: "+22.10%",
        signalDate: "15 Sep 2025",
        expectedProphit: "Expected profit",
        statusColor: "bg-red-500",
        targetBuy: "$33.120",
        stopLoss: "$30.000",
        mostRecentExit: "---",
        targetSale1: "$40.320",
        targetSale2: "$49.500",
        realizedGained: "-12.542%",
        unrealizedGained: "0%",
        chart: SwingTradeGraph
    },
    {
        symbol: "AMZN.O",
        name: "Amazon Inc",
        mark: "+98.21%",
        signalDate: "15 Sep 2025",
        expectedProphit: "Expected profit",
        statusColor: "bg-red-500",
        targetBuy: "$40.256",
        stopLoss: "$37.466",
        mostRecentExit: "---",
        targetSale1: "$45.350",
        targetSale2: "$49.500",
        realizedGained: "-10.200%",
        unrealizedGained: "0%",
        chart: SwingTradeGraph
    },
    {
        symbol: "Alpha.X",
        name: "Alpha.X",
        mark: "+38.7%",
        signalDate: "15 Sep 2025",
        expectedProphit: "Expected profit",
        statusColor: "bg-red-500",
        targetBuy: "$24.56",
        stopLoss: "$24.56",
        mostRecentExit: "$24.63",
        targetSale1: "$24.63",
        targetSale2: "$23.58",
        realizedGained: "+38.7%",
        unrealizedGained: "0%",
        chart: SwingTradeGraph
    },
    {
        symbol: "Beta.Y",
        name: "Beta Enterprices",
        mark: "+42.10%",
        signalDate: "15 Sep 2025",
        expectedProphit: "Possible gain",
        statusColor: "bg-red-500",
        targetBuy: "$40.256",
        stopLoss: "$37.466",
        mostRecentExit: "---",
        targetSale1: "$45.350",
        targetSale2: "$49.500",
        realizedGained: "-10.200%",
        unrealizedGained: "0%",
        chart: SwingTradeGraph
    },
    {
        symbol: "Gamma.Z",
        name: "Gamma Solutions",
        mark: "+22.10%",
        signalDate: "15 Sep 2025",
        expectedProphit: "Expected profit",
        statusColor: "bg-red-500",
        targetBuy: "$33.120",
        stopLoss: "$30.000",
        mostRecentExit: "---",
        targetSale1: "$40.320",
        targetSale2: "$49.500",
        realizedGained: "-12.542%",
        unrealizedGained: "0%",
        chart: SwingTradeGraph
    },
    {
        symbol: "AMZN.O",
        name: "Amazon Inc",
        mark: "+98.21%",
        signalDate: "15 Sep 2025",
        expectedProphit: "Expected profit",
        statusColor: "bg-red-500",
        targetBuy: "$40.256",
        stopLoss: "$37.466",
        mostRecentExit: "---",
        targetSale1: "$45.350",
        targetSale2: "$49.500",
        realizedGained: "-10.200%",
        unrealizedGained: "0%",
        chart: SwingTradeGraph
    },
    {
        symbol: "Alpha.X",
        name: "Alpha.X",
        mark: "+38.7%",
        signalDate: "15 Sep 2025",
        expectedProphit: "Expected profit",
        statusColor: "bg-red-500",
        targetBuy: "$24.56",
        stopLoss: "$24.56",
        mostRecentExit: "$24.63",
        targetSale1: "$24.63",
        targetSale2: "$23.58",
        realizedGained: "+38.7%",
        unrealizedGained: "0%",
        chart: SwingTradeGraph
    },
    {
        symbol: "Beta.Y",
        name: "Beta Enterprices",
        mark: "+42.10%",
        signalDate: "15 Sep 2025",
        expectedProphit: "Possible gain",
        statusColor: "bg-red-500",
        targetBuy: "$40.256",
        stopLoss: "$37.466",
        mostRecentExit: "---",
        targetSale1: "$45.350",
        targetSale2: "$49.500",
        realizedGained: "-10.200%",
        unrealizedGained: "0%",
        chart: SwingTradeGraph
    },
    {
        symbol: "Gamma.Z",
        name: "Gamma Solutions",
        mark: "+22.10%",
        signalDate: "15 Sep 2025",
        expectedProphit: "Expected profit",
        statusColor: "bg-red-500",
        targetBuy: "$33.120",
        stopLoss: "$30.000",
        mostRecentExit: "---",
        targetSale1: "$40.320",
        targetSale2: "$49.500",
        realizedGained: "-12.542%",
        unrealizedGained: "0%",
        chart: SwingTradeGraph
    },
    {
        symbol: "AMZN.O",
        name: "Amazon Inc",
        mark: "+98.21%",
        signalDate: "15 Sep 2025",
        expectedProphit: "Expected profit",
        statusColor: "bg-red-500",
        targetBuy: "$40.256",
        stopLoss: "$37.466",
        mostRecentExit: "---",
        targetSale1: "$45.350",
        targetSale2: "$49.500",
        realizedGained: "-10.200%",
        unrealizedGained: "0%",
        chart: SwingTradeGraph
    },
    {
        symbol: "Alpha.X",
        name: "Alpha.X",
        mark: "+38.7%",
        signalDate: "15 Sep 2025",
        expectedProphit: "Expected profit",
        statusColor: "bg-red-500",
        targetBuy: "$24.56",
        stopLoss: "$24.56",
        mostRecentExit: "$24.63",
        targetSale1: "$24.63",
        targetSale2: "$23.58",
        realizedGained: "+38.7%",
        unrealizedGained: "0%",
        chart: SwingTradeGraph
    },
    {
        symbol: "Beta.Y",
        name: "Beta Enterprices",
        mark: "+42.10%",
        signalDate: "15 Sep 2025",
        expectedProphit: "Possible gain",
        statusColor: "bg-red-500",
        targetBuy: "$40.256",
        stopLoss: "$37.466",
        mostRecentExit: "---",
        targetSale1: "$45.350",
        targetSale2: "$49.500",
        realizedGained: "-10.200%",
        unrealizedGained: "0%",
        chart: SwingTradeGraph
    },
    {
        symbol: "Gamma.Z",
        name: "Gamma Solutions",
        mark: "+22.10%",
        signalDate: "15 Sep 2025",
        expectedProphit: "Expected profit",
        statusColor: "bg-red-500",
        targetBuy: "$33.120",
        stopLoss: "$30.000",
        mostRecentExit: "---",
        targetSale1: "$40.320",
        targetSale2: "$49.500",
        realizedGained: "-12.542%",
        unrealizedGained: "0%",
        chart: SwingTradeGraph
    },
    {
        symbol: "AMZN.O",
        name: "Amazon Inc",
        mark: "+98.21%",
        signalDate: "15 Sep 2025",
        expectedProphit: "Expected profit",
        statusColor: "bg-red-500",
        targetBuy: "$40.256",
        stopLoss: "$37.466",
        mostRecentExit: "---",
        targetSale1: "$45.350",
        targetSale2: "$49.500",
        realizedGained: "-10.200%",
        unrealizedGained: "0%",
        chart: SwingTradeGraph
    },
    {
        symbol: "Alpha.X",
        name: "Alpha.X",
        mark: "+38.7%",
        signalDate: "15 Sep 2025",
        expectedProphit: "Expected profit",
        statusColor: "bg-red-500",
        targetBuy: "$24.56",
        stopLoss: "$24.56",
        mostRecentExit: "$24.63",
        targetSale1: "$24.63",
        targetSale2: "$23.58",
        realizedGained: "+38.7%",
        unrealizedGained: "0%",
        chart: SwingTradeGraph
    },
    {
        symbol: "Beta.Y",
        name: "Beta Enterprices",
        mark: "+42.10%",
        signalDate: "15 Sep 2025",
        expectedProphit: "Possible gain",
        statusColor: "bg-red-500",
        targetBuy: "$40.256",
        stopLoss: "$37.466",
        mostRecentExit: "---",
        targetSale1: "$45.350",
        targetSale2: "$49.500",
        realizedGained: "-10.200%",
        unrealizedGained: "0%",
        chart: SwingTradeGraph
    },
    {
        symbol: "Gamma.Z",
        name: "Gamma Solutions",
        mark: "+22.10%",
        signalDate: "15 Sep 2025",
        expectedProphit: "Expected profit",
        statusColor: "bg-red-500",
        targetBuy: "$33.120",
        stopLoss: "$30.000",
        mostRecentExit: "---",
        targetSale1: "$40.320",
        targetSale2: "$49.500",
        realizedGained: "-12.542%",
        unrealizedGained: "0%",
        chart: SwingTradeGraph
    },
    {
        symbol: "AMZN.O",
        name: "Amazon Inc",
        mark: "+98.21%",
        signalDate: "15 Sep 2025",
        expectedProphit: "Expected profit",
        statusColor: "bg-red-500",
        targetBuy: "$40.256",
        stopLoss: "$37.466",
        mostRecentExit: "---",
        targetSale1: "$45.350",
        targetSale2: "$49.500",
        realizedGained: "-10.200%",
        unrealizedGained: "0%",
        chart: SwingTradeGraph
    },
    {
        symbol: "Alpha.X",
        name: "Alpha.X",
        mark: "+38.7%",
        signalDate: "15 Sep 2025",
        expectedProphit: "Expected profit",
        statusColor: "bg-red-500",
        targetBuy: "$24.56",
        stopLoss: "$24.56",
        mostRecentExit: "$24.63",
        targetSale1: "$24.63",
        targetSale2: "$23.58",
        realizedGained: "+38.7%",
        unrealizedGained: "0%",
        chart: SwingTradeGraph
    },
    {
        symbol: "Beta.Y",
        name: "Beta Enterprices",
        mark: "+42.10%",
        signalDate: "15 Sep 2025",
        expectedProphit: "Possible gain",
        statusColor: "bg-red-500",
        targetBuy: "$40.256",
        stopLoss: "$37.466",
        mostRecentExit: "---",
        targetSale1: "$45.350",
        targetSale2: "$49.500",
        realizedGained: "-10.200%",
        unrealizedGained: "0%",
        chart: SwingTradeGraph
    },
    {
        symbol: "Gamma.Z",
        name: "Gamma Solutions",
        mark: "+22.10%",
        signalDate: "15 Sep 2025",
        expectedProphit: "Expected profit",
        statusColor: "bg-red-500",
        targetBuy: "$33.120",
        stopLoss: "$30.000",
        mostRecentExit: "---",
        targetSale1: "$40.320",
        targetSale2: "$49.500",
        realizedGained: "-12.542%",
        unrealizedGained: "0%",
        chart: SwingTradeGraph
    },
    {
        symbol: "AMZN.O",
        name: "Amazon Inc",
        mark: "+98.21%",
        signalDate: "15 Sep 2025",
        expectedProphit: "Expected profit",
        statusColor: "bg-red-500",
        targetBuy: "$40.256",
        stopLoss: "$37.466",
        mostRecentExit: "---",
        targetSale1: "$45.350",
        targetSale2: "$49.500",
        realizedGained: "-10.200%",
        unrealizedGained: "0%",
        chart: SwingTradeGraph
    },
    {
        symbol: "Alpha.X",
        name: "Alpha.X",
        mark: "+38.7%",
        signalDate: "15 Sep 2025",
        expectedProphit: "Expected profit",
        statusColor: "bg-red-500",
        targetBuy: "$24.56",
        stopLoss: "$24.56",
        mostRecentExit: "$24.63",
        targetSale1: "$24.63",
        targetSale2: "$23.58",
        realizedGained: "+38.7%",
        unrealizedGained: "0%",
        chart: SwingTradeGraph
    },
    {
        symbol: "Beta.Y",
        name: "Beta Enterprices",
        mark: "+42.10%",
        signalDate: "15 Sep 2025",
        expectedProphit: "Possible gain",
        statusColor: "bg-red-500",
        targetBuy: "$40.256",
        stopLoss: "$37.466",
        mostRecentExit: "---",
        targetSale1: "$45.350",
        targetSale2: "$49.500",
        realizedGained: "-10.200%",
        unrealizedGained: "0%",
        chart: SwingTradeGraph
    },
    {
        symbol: "Gamma.Z",
        name: "Gamma Solutions",
        mark: "+22.10%",
        signalDate: "15 Sep 2025",
        expectedProphit: "Expected profit",
        statusColor: "bg-red-500",
        targetBuy: "$33.120",
        stopLoss: "$30.000",
        mostRecentExit: "---",
        targetSale1: "$40.320",
        targetSale2: "$49.500",
        realizedGained: "-12.542%",
        unrealizedGained: "0%",
        chart: SwingTradeGraph
    },
    {
        symbol: "AMZN.O",
        name: "Amazon Inc",
        mark: "+98.21%",
        signalDate: "15 Sep 2025",
        expectedProphit: "Expected profit",
        statusColor: "bg-red-500",
        targetBuy: "$40.256",
        stopLoss: "$37.466",
        mostRecentExit: "---",
        targetSale1: "$45.350",
        targetSale2: "$49.500",
        realizedGained: "-10.200%",
        unrealizedGained: "0%",
        chart: SwingTradeGraph
    },
    {
        symbol: "Alpha.X",
        name: "Alpha.X",
        mark: "+38.7%",
        signalDate: "15 Sep 2025",
        expectedProphit: "Expected profit",
        statusColor: "bg-red-500",
        targetBuy: "$24.56",
        stopLoss: "$24.56",
        mostRecentExit: "$24.63",
        targetSale1: "$24.63",
        targetSale2: "$23.58",
        realizedGained: "+38.7%",
        unrealizedGained: "0%",
        chart: SwingTradeGraph
    },
    {
        symbol: "Beta.Y",
        name: "Beta Enterprices",
        mark: "+42.10%",
        signalDate: "15 Sep 2025",
        expectedProphit: "Possible gain",
        statusColor: "bg-red-500",
        targetBuy: "$40.256",
        stopLoss: "$37.466",
        mostRecentExit: "---",
        targetSale1: "$45.350",
        targetSale2: "$49.500",
        realizedGained: "-10.200%",
        unrealizedGained: "0%",
        chart: SwingTradeGraph
    },
    {
        symbol: "Gamma.Z",
        name: "Gamma Solutions",
        mark: "+22.10%",
        signalDate: "15 Sep 2025",
        expectedProphit: "Expected profit",
        statusColor: "bg-red-500",
        targetBuy: "$33.120",
        stopLoss: "$30.000",
        mostRecentExit: "---",
        targetSale1: "$40.320",
        targetSale2: "$49.500",
        realizedGained: "-12.542%",
        unrealizedGained: "0%",
        chart: SwingTradeGraph
    },
    {
        symbol: "AMZN.O",
        name: "Amazon Inc",
        mark: "+98.21%",
        signalDate: "15 Sep 2025",
        expectedProphit: "Expected profit",
        statusColor: "bg-red-500",
        targetBuy: "$40.256",
        stopLoss: "$37.466",
        mostRecentExit: "---",
        targetSale1: "$45.350",
        targetSale2: "$49.500",
        realizedGained: "-10.200%",
        unrealizedGained: "0%",
        chart: SwingTradeGraph
    },
];